# Generated by Django 4.2.5 on 2023-09-16 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Electronicsstore', '0002_devices_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='devices',
            name='type',
            field=models.CharField(choices=[('Technology', 'Technology'), ('Household devices', 'Household devices')], max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='devices',
            name='mark',
            field=models.CharField(choices=[('Iphone', 'Iphone'), ('Samsung', 'Samsung'), ('Huawei', 'Huawei'), ('LG', 'LG'), ('Sony', 'Sony'), ('TOSHIBA', 'TOSHIBA')], max_length=60, null=True),
        ),
    ]
