# Generated by Django 4.2.5 on 2023-09-16 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Electronicsstore', '0003_devices_type_alter_devices_mark'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Electronicsstore.customer'),
        ),
        migrations.AddField(
            model_name='order',
            name='devices',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Electronicsstore.devices'),
        ),
    ]
