# Generated by Django 4.2.5 on 2023-09-18 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Electronicsstore', '0004_order_customer_order_devices'),
    ]

    operations = [
        migrations.RenameField(
            model_name='devices',
            old_name='type',
            new_name='devices',
        ),
    ]
