# Generated by Django 4.2.5 on 2023-09-18 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Electronicsstore', '0005_rename_type_devices_devices'),
    ]

    operations = [
        migrations.RenameField(
            model_name='devices',
            old_name='devices',
            new_name='type',
        ),
    ]
