# Generated by Django 4.2.5 on 2024-02-15 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Electronicsstore', '0007_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductTwo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
